### ISSUE TITLE
Modification indices

### ISSUE THREAD

**Issue by AdamVotava** [ecmerkle/blavaan#1]
Hi,

thanks a lot for a very useful package! I tried to get modification indices via `summary(object, modindices=T)` but keep getting an error (`arguments imply differing number of rows`) when fitting the extended `lavaan` object in `lav_object_extended()`.

Do you have any idea why it's not working?

Thanks,
Adam

**Comment by ecmerkle** [comment]
Adam,

I suspect this error is related to some changes that blavaan makes to the parameter table. I will have to check it out.

I am also uncertain that modification indices should be calculated this way for a Bayesian model; I will have to give it some more thought.

Ed


On 08/02/2016 08:32 AM, AdamVotava wrote:

Hi,

thanks a lot for a very useful package! I tried to get modification indices via summary(object, modindices=T) but keep getting an error (arguments imply differing number of rows) when fitting the extended lavaan object in lav_object_extended().

Do you have any idea why it's not working?

Thanks,
Adam

**Comment by ecmerkle** [comment]
Adam,

I looked at this again and ended up removing the "modindices" argument from summary(). This argument was attempting to compare the estimated Bayesian model to a frequentist model with freed parameters (where the modification indices stem from this comparison). I think this is misleading/confusing because it is part Bayesian and part frequentist. The functionality was only there to begin with because blavaan utilizes many other functions within lavaan.

It may be possible to do a fully Bayesian modification index that incorporates the priors, but it is not implemented and may be computationally intensive (i.e., slow).

Best,
Ed
