### ISSUE TITLE
convert custom jags model to a lavaan object?

### ISSUE THREAD

**Issue by dustinfife** [ecmerkle/blavaan#20]
I'm developing a custom jags model through blavaan using the mcmcfile=T option, then editing that file directly. I have successfully run that file in jags, but it doesn't return a lavaan object. My code later down the line requires it to be a lavaan object. Is there a way to pass a jags file through blavaan rather than lavaan syntax?

**Comment by ecmerkle** [comment]
There is not a general way to do this, because I don't have a general way to know whether the modified jags file is a model that blavaan knows. For example, if you changed the normal distributions to t-distributions in the jags model, blavaan wouldn't be able to compute the correct likelihoods or other metrics even if you could send the jags model back.

If your modifications only involve adding lines to the original jags model, see the `mcmcextra` argument. This argument allows you to specify additional code that should be added to the jags file, beyond the regular jags specification. Or, if you tell me more about the modifications, maybe I get some other ideas...

**Comment by dustinfife** [comment]
That makes sense. Here's what I'm trying to do: As far as I can tell, lavaan syntax only allows linear paths, but I want to have one path (say from observed latent F to observed X1) be nonlinear (say mu[i,3] <- nu[3,1,g[i]]^*eta[i,1]). I may also want to specify that X1 follows a chisquare, but it sounds like that part cannot be modeled with lavaan.

**Comment by ecmerkle** [comment]
I think this nonlinear relationship is enough to not get what you want out of a (b)lavaan object. But I wonder whether you could do something similar by log-transforming X1 before you send it to the model. Then, based on the equation you wanted for X1 (before the log), mu[i,3] would implicitly become something like

`nu[3,1,g[i]] + log(lambda) * eta[i,1]
`

which is again linear, so should be do-able with regular lavaan syntax.

**Comment by dustinfife** [comment]
Thanks for the suggestion. I actually did get it to recognize mu[i,3] <- nu[3,1,g[i]]^*eta[i,1]) as lavaan syntax using mcmcextra. Thanks for the suggestion!

In general, I'm finding it unusually difficult to develop predictions from bayesian models. I'm not sure if it's because I'm a bayesian novice, or if the problem itself is quite tricky. Regardless, thanks for the help!

**Comment by ecmerkle** [comment]
Glad to hear that it worked. I might still distrust some of the blavaan object output, like DIC and WAIC, because I'm not sure that those will correctly recognize your modifications to the jags file.

For the models with latent variables (or random effects in a multilevel context), prediction becomes tricky because you can get predictions that include latent variables, or predictions that do not include latent variables. And that is different from maximum likelihood models, where they often do not include latent variables in predictions. I have a paper discussing this distinction in detail (in the context of DIC and WAIC), though it is a bit technical:

https://arxiv.org/pdf/1802.04452

**Comment by dustinfife** [comment]
This might explain some of my results I'm getting. Long story short, I'm trying to create "residual plots" for sem. Suppose we have a dataset `d` and a blavaan model `mod` that is just a simple factor analysis with three indicators. To create a residual plot, I am using the following:
`
d$fitted = lavPredict(mod)
d$residuals = residuals(lm(x2~fitted, data=d))
with(d, plot(x1, residuals))
`
I would expect the line to be flat (because, presumably we have removed any relationship between x1 and x2 via the latent variable), but it's not flat; there's still an association between x1/x2 even after removing the estimated latent variable scores. Is that because `lavPredict` is using using a conditional likelihood (or conditional likelihood)?

**Comment by ecmerkle** [comment]
I don't think that is a conditional/marginal likelihood issue. Instead, I think it is a "local dependence" issue. The model assumes that the observed variables are independent conditioned on the latent variable, but the data don't have to agree with that assumption. It might be impossible for the latent variable to fully account for the correlations between observed variables. If you google for things like "local dependence" or "residual covariance", you should be able to find more info there.

**Comment by dustinfife** [comment]
Could that still be the case if the data are simulated with very large sample sizes?

**Comment by dustinfife** [comment]
Here's an example:

```
n = 10000
slopes = .7
latent = rnorm(n)

# create three indicators
x1 = slopes*latent + rnorm(n,0, sqrt(1-slopes^2))
x2 = slopes*latent + rnorm(n,0, sqrt(1-slopes^2))
x3 = slopes*latent + rnorm(n,0, sqrt(1-slopes^2))
d = data.frame(x1=x1, x2=x2, x3=x3)

# model in lavaan
model.linear = '
  A =~ NA*x1 + x2 + x3
  A ~~ 1*A
'
require(lavaan)
fitted = cfa(model.linear, data=d)

# create residuals
observed.vars = lavNames(fitted, type="ov")
lav_residuals = d[,observed.vars] - lavPredict(fitted, type="ov")

plot(x3~x2, data=lav_residuals)
abline(lm(x3~x2, data=lav_residuals))
plot(x3~x1, data=lav_residuals)
abline(lm(x3~x1, data=lav_residuals))
plot(x1~x2, data=lav_residuals)
abline(lm(x1~x2, data=lav_residuals))
```

I'm going to send you an email with more info.

**Comment by ecmerkle** [comment]
I suspect that there is an explanation for what is going on here (related to how factor scores are computed), but I don't immediately know it. You might try the lavaan google group (url below), where there are lots of knowledgeable people who might be able to provide a better response.

https://groups.google.com/forum/#!forum/lavaan

**Comment by dustinfife** [comment]
Thanks for the reply. I think it's actually measurement error. I believe the predicted values assume no measurement error, which leads to a systematic bias. I'm working on the math right now. I'll send you an update when I get things worked out.

Thanks again for being so helpful!
