### ISSUE TITLE
model results become different when save.lvs = TRUE

### ISSUE THREAD

**Issue by littlehifive** [ecmerkle/blavaan#47]
Hi Ed,

I am wondering why the model result is different when `save.lvs = T`, even under the same random seed. My main model converges well, but when I added `save.lvs = T` to save the factor scores, it fails to converge. I am attaching below a minimal example. Although both model converges in the example, they do have different results. All variables are Likert-scale survey items on an ordinal scale. Thanks!

[test.csv](https://github.com/ecmerkle/blavaan/files/8478083/test.csv)

```
test_model <- '
  # measurement model
  PSRA =~ PSRA1_1 + PSRA2_1 + PSRA3_1 + PSRA4_1 + PSRA5_1 + PSRA6_1 + PSRA7_1 + PSRA8_1 + PSRA10_1 + PSRA11_1 + PSRA12_1 + PSRA13_1
'

mydp <- dpriors(tau = "normal(0, 0.5)",
                lambda = "normal(0, 2)")

# model 1
fit_1 <- bcfa(test_model, data = test,
            ordered = c("PSRA1_1", "PSRA2_1", "PSRA3_1",
                        "PSRA4_1", "PSRA5_1", "PSRA6_1",
                        "PSRA7_1", "PSRA8_1", "PSRA10_1",
                        "PSRA11_1", "PSRA12_1", "PSRA13_1"),
           dp = mydp,
           std.lv=TRUE,
           # save.lvs=TRUE,
           mcmcextra = list(data = list(llnsamp = 200)),
           n.chains = 4,
           seed = 1234)

# model 2
fit_2 <- bcfa(test_model, data = test,
            ordered = c("PSRA1_1", "PSRA2_1", "PSRA3_1",
                        "PSRA4_1", "PSRA5_1", "PSRA6_1",
                        "PSRA7_1", "PSRA8_1", "PSRA10_1",
                        "PSRA11_1", "PSRA12_1", "PSRA13_1"),
           dp = mydp,
           std.lv=TRUE,
           save.lvs=TRUE,
           mcmcextra = list(data = list(llnsamp = 200)),
           n.chains = 4,
           seed = 1234)
```

**Comment by ecmerkle** [comment]
Thanks for the report! I think this is happening because the `pars` argument to Stan changes depending on the value of `save.lvs`, which seems to influence the randomization in Stan. The `save.lvs=TRUE` setting should not influence convergence because it does not change anything in the Stan model.

I have found that the ordinal models fail to converge more often than the continuous models due to sign flipping of loadings. In many cases, I think the priors on the loadings should not be symmetric around 0, and this can also help convergence. For example, if you know that all the items should "load" in the same direction (i.e., higher categories of the item imply larger values of the latent variable), then maybe the prior should be something like normal(.75,.5). Or, if std.lv=FALSE, I would set the prior means at 1 because we are fixing a loading to 1 already, and I might expect other items to behave similarly.

**Comment by littlehifive** [comment]
@bgoodri

**Comment by ecmerkle** [comment]
I looked at this a bit more and (unsurprisingly) found the problem is not Stan. It is that blavaan sends random starting values to Stan every time you run the model, which can influence posterior samples. To use the same starting values each time (which should lead to the same posterior samples), it is easiest to use the blavaan argument `inits = "simple"`. It might also work if you fix the seed in R before running the model.

**Comment by littlehifive** [comment]
Thank you! For my example models, setting a global seed with `set.seed(1234)` doesn't seem to work, but `inits = "simple"` works!

**Comment by ecmerkle** [comment]
Some other randomization must happen before blavaan gets to the initial values, which changes the randomly-generated inits.

If you wanted to manually set your initial values, you could run the model with the argument `do.fit = FALSE`. Then

```r
myinits <- blavInspect(fit, "inits")
```

Then modify `myinits` as you like, then re-run your model with the argument `inits = myinits`.
