### ISSUE TITLE
Growth Mrxture Modelling in blavaan

### ISSUE THREAD

**Issue by AndreasHani** [ecmerkle/blavaan#55]
Hi Ed,

is it possible to do Growth Mixture Modelling with blavaan? If this is the case, could you tell me which function I should use for this task?

Many thanks in advance
Andreas

**Comment by ecmerkle** [comment]
Andreas, it is not currently possible in blavaan. 

If you wanted to export the blavaan Stan (or JAGS) code for a regular growth model, it might be feasible to modify the code to do mixtures. This is because there is a "group" indexing variable for multi-group models, which could also be used as mixture components if the groups are treated as parameters. But you would also have to handle identification issues associated with mixtures. I could advise more if you are interested in attempting it.
