### ISSUE TITLE
build package on Ubuntu

### ISSUE THREAD

**Issue by hyunsooseol** [ecmerkle/blavaan#85]
Hi

I'm building a R package on Ubuntu, but it takes too long to build because of the 'blavaan' R package. In the end, I failed to build it due to the hard capacity and memory problem of my computer, which resulted in an infinite loop. I'm wondering if there is a problem with the build and if there is any other way to reduce the build time. Thanks in advance.

Cheers
Seol

**Comment by ecmerkle** [comment]
Thanks for the report. Could you clarify how you are installing the package? i.e., are you installing from CRAN or from github, are you using install.packages() or some other method, etc.

Sometimes it is helpful to first try installing the rstan package, then run a test model in rstan (from the bottom of ?stan). This provides information about whether the installation problem happens with rstan (which is a blavaan dependency), as opposed to blavaan.

Also, in case you don't know about it: I highly recommend r2u for installing R packages on Ubuntu: https://eddelbuettel.github.io/r2u/

**Comment by hyunsooseol** [comment]
Hi 
Thank you for your kind comments.  
I am a module developer of the open source statistical program called jamovi(https://www.jamovi.org).  I am trying to build a module called snowRMM on Ubuntu.

I need to install blavaan as a tidySEM R package dependency in the snowRMM module.
 During the building process, it asked for rstan and I installed it before installing blavaan. Next, it took a long time to install blavaan and eventually failed to install it due to hard disk capacity and memory problems of my computer. so I thought it's a huge package compared to other R packages.  so is there any way to build blavaan quickly(or efficiently)?  it takes over 1500 seconds to build and eventually gets stuck in an infinite loop.
 
 Cheers
 Seol

**Comment by ecmerkle** [comment]
It takes a long time because it is compiling a gigantic Stan file, which is then used to estimate all the models that users request. This saves times for users (they do not have to compile every time they request a new model), but it makes the installation memory intensive. 

It may be possible to create a binary where the Stan model is already compiled, in the same way that r2u does it. Or if you only need blavaan installed on your local system, then installing from r2u might solve the problem for you. But if you need to build from the blavaan source, there is currently no way to get around the big Stan model compilation.

**Comment by hyunsooseol** [comment]
Hi
Thank you for your great advice. Once again, thank you very much !

Cheers
Seol
