### ISSUE TITLE
upper bound on observed variance?

### ISSUE THREAD

**Issue by jpritikin** [ecmerkle/blavaan#87]
The maximum variance of Likert ordinal observed variables depends on the number of outcomes:

````
> var(rep(1:5, 100))
[1] 2
> var(rep(1:3, 100))
[1] 0.669
> var(rep(1:2, 100))
[1] 0.251
````

If would be great to be able to put an upper bound on the variance. Otherwise it is difficult to keep the model from drifting outside of the sane parameter space with mere priors.

**Comment by jpritikin** [comment]
Maybe I am misdiagnosing the problem.

**Comment by ecmerkle** [comment]
Yes, I think this would only matter if the model was treating the ordinal variables as though they were continuous. 

If the model is treating the ordinal variables as ordinal, then the variance parameters are on the "latent underlying continuous" scale instead of directly applying to the ordinal scale. The variances are used to compute probabilities of being in each ordinal category, and their exact values depend on the identification constraints. For example, maybe one identification constraint leads to a predicted probability of `pnorm(-1, sd = 1)` while a different identification constraint leads to a predicted probability of `pnorm(-3, sd = 3)`. They both get you to the same place even though the variances are different.
